-- Flyway migration: create candidate table
CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(255),
    party VARCHAR(255),
    office VARCHAR(255),
    region_code VARCHAR(255),
    election_type VARCHAR(255),
    slogan VARCHAR(255),
    platform_statement VARCHAR(3000),
    previous_political_experience VARCHAR(3000),
    photo_url VARCHAR(255),
    status VARCHAR(255),
    declared_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES app_user(id)
); 