-- Flyway migration: create election table
CREATE TABLE election (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    region VARCHAR(255),
    office VARCHAR(255),
    election_type VARCHAR(255) NOT NULL,
    voting_system VARCHAR(255),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    status VARCHAR(255) NOT NULL
); 