-- Flyway migration: create pledged_votes table
CREATE TABLE pledged_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    bill_id BIGINT NOT NULL,
    vote_option VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (bill_id) REFERENCES bills(id)
); 