-- Flyway migration: create polling tables
CREATE TABLE polling_firm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000),
    user_id BIGINT,
    is_approved BOOLEAN,
    reputation_score INT,
    bias_rating VARCHAR(255)
);

CREATE TABLE election (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL
);

CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    pollster VARCHAR(255),
    election_type VARCHAR(255),
    region VARCHAR(255),
    firm_id BIGINT,
    election_id BIGINT,
    sample_size INT,
    methodology VARCHAR(255),
    start_date DATE,
    end_date DATE,
    margin_of_error DOUBLE,
    is_published BOOLEAN,
    FOREIGN KEY (firm_id) REFERENCES polling_firm(id),
    FOREIGN KEY (election_id) REFERENCES election(id)
);

CREATE TABLE poll_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    candidate_name VARCHAR(255),
    percentage DOUBLE,
    FOREIGN KEY (poll_id) REFERENCES poll(id)
); 