-- Flyway migration: create polling tables
CREATE TABLE polling_firm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    founding_year INTEGER,
    methodology TEXT,
    house_effects TEXT,
    bias_rating VARCHAR(255)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'election'
    ) THEN
        CREATE TABLE election (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            date DATE NOT NULL
        );
    END IF;
END $$;

CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    pollster VARCHAR(255),
    election_type VARCHAR(255),
    region VARCHAR(255),
    firm_id BIGINT,
    election_id BIGINT,
    sample_size INT,
    methodology VARCHAR(255),
    start_date DATE,
    end_date DATE,
    margin_of_error DOUBLE,
    is_published BOOLEAN,
    FOREIGN KEY (firm_id) REFERENCES polling_firm(id),
    FOREIGN KEY (election_id) REFERENCES election(id)
);

CREATE TABLE poll_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    candidate_name VARCHAR(255),
    percentage DOUBLE,
    FOREIGN KEY (poll_id) REFERENCES poll(id)
); 