-- Flyway migration: create user_role table
CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    region_id VARCHAR(255),
    start_date DATE,
    end_date DATE,
    active BOOLEAN,
    FOREIGN KEY (app_user_id) REFERENCES app_user(id)
); 