-- Flyway migration: create bill table
CREATE TABLE bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    sponsor_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    voted_at TIMESTAMP,
    FOREIGN KEY (sponsor_id) REFERENCES app_user(id)
); 