-- Flyway migration: create amendment table
CREATE TABLE amendment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL,
    sponsor_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (bill_id) REFERENCES bills(id),
    FOREIGN KEY (sponsor_id) REFERENCES app_user(id)
); 