-- Flyway migration: create news_agency table
CREATE TABLE news_agency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    logo_url VARCHAR(255),
    slogan VARCHAR(255),
    editorial_stance VARCHAR(255),
    founder_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (founder_id) REFERENCES app_user(id)
);

CREATE TABLE news_agency_staff (
    news_agency_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (news_agency_id, user_id),
    FOREIGN KEY (news_agency_id) REFERENCES news_agency(id),
    FOREIGN KEY (user_id) REFERENCES app_user(id)
); 