-- Flyway migration: create article, article_bias, and comment tables
CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headline VARCHAR(255) NOT NULL,
    body CLOB NOT NULL,
    tags VARCHAR(255),
    news_agency_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    published_at TIMESTAMP,
    likes INT NOT NULL,
    shares INT NOT NULL,
    visibility_level DOUBLE NOT NULL,
    impact_modifier DOUBLE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (news_agency_id) REFERENCES news_agency(id),
    FOREIGN KEY (author_id) REFERENCES app_user(id)
);

CREATE TABLE article_bias (
    id BIGINT PRIMARY KEY,
    bias_classification VARCHAR(255),
    emotional_charge_score DOUBLE,
    misleading_language_score DOUBLE,
    suggested_tags TEXT,
    analysis_notes TEXT,
    analysis_timestamp TIMESTAMP,
    FOREIGN KEY (id) REFERENCES article(id)
);

CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB NOT NULL,
    article_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (article_id) REFERENCES article(id),
    FOREIGN KEY (author_id) REFERENCES app_user(id),
    FOREIGN KEY (parent_comment_id) REFERENCES comment(id)
); 